version: "3"
services:
    scheduler_server:
        build:
            context: ./job_scheduler/server
            dockerfile: Dockerfile.dev
        ports:
            - "9090:9090"
        networks:
            - databases
        volumes:
            - ./job_scheduler/server:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - REDIS_HOST=redis
            - AO_API_URL=http://ao-api:3004
        command: npm run dev

    ui:
        build:
            context: ./ui
            dockerfile: Dockerfile.dev
        ports:
            - "3010:80"
        networks:
            - databases
        volumes:
            - ./ui:/usr/src/app
            - ./ui/nginx.conf:/etc/nginx/nginx.conf
            - /usr/src/app/node_modules
        env_file:
            - ./ui/.env.development

    ui_builder:
        build: 
            context: ./ui-builder
            dockerfile: Dockerfile
        environment:
            - NODE_OPTIONS=--max_old_space_size=2048
        ports:
            - '8090:80'
        networks:
            - databases
        volumes:
            - ./ui-builder:/usr/src/app
            - ./ui-builder/nginx.conf:/etc/nginx/nginx.conf
            - /usr/src/app/node_modules
    
    ui_ecommerce:
        build:
            context: ./ui-ecommerce
            dockerfile: Dockerfile
        ports:
            - "3011:80"
        networks:
            - databases
        volumes:
            - ./ui-ecommerce:/usr/src/app
            - ./ui-ecommerce/nginx.conf:/etc/nginx/nginx.conf
            - /usr/src/app/node_modules
        env_file:
            - ./ui-ecommerce/.env.development
    
    ui_form:
        build:
            context: ./ui-form
            dockerfile: Dockerfile
        ports:
            - "3012:80"
        networks:
            - databases
        volumes:
            - ./ui-form:/usr/src/app
            - ./ui-form/nginx.conf:/etc/nginx/nginx.conf
            - /usr/src/app/node_modules
        env_file:
            - ./ui-form/.env.development

    ao-api:
        build:
            context: .
            dockerfile: ./ao-api/Dockerfile
        env_file:
            - ./ao-api/.env
        environment:
            - RUNNING_IN_DOCKER=true
        depends_on:
            - scheduler_server
        hostname: ao-api
        working_dir: /root/
        volumes:
            - ao_api_data:/go/src/github.com/dotenx/dotenx/ao-api
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - databases
        ports:
            - "3005:3004"
        expose:
            - 3005

    runner:
        build:
            context: runner
            dockerfile: Dockerfile.dev
        working_dir: /root/
        volumes:
            - /tmp/cache:/tmp/cache
            - runner_data:/go/src/github.com/dotenx/dotenx/runner
            - /var/run/docker.sock:/var/run/docker.sock
        networks:
            - databases

networks:
  databases:
    external:
      name: databases

volumes:
    ao_api_data:
    runner_data:
