version: "3"
services:

    redis:
        image: redis
        hostname: redis
        ports:
            - "6380:6379"
        volumes:
            - "redis_data:/data"
        networks:
            - databases

    psql:
        image: postgres:12
        hostname: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: postgres
            POSTGRES_HOST_AUTH_METHOD: scram-sha-256
        volumes:
            - "postgres_data:/var/lib/postgresql/data/"
            - "./pg_hba.conf:/etc/postgresql/pg_hba.conf:ro"
            - "./postgresql.conf:/etc/postgresql/postgresql.conf:ro"
        command: postgres -c config_file=/etc/postgresql/postgresql.conf -c hba_file=/etc/postgresql/pg_hba.conf
        ports:
            - "5432:5432"
        expose:
            - 5432
        restart: unless-stopped
        networks:
            - databases

networks:
  databases:
    name: databases
    driver: overlay
    attachable: true

volumes:
    redis_data:
    postgres_data: